services:
  backend:
    build:
      context: ./backend
    environment:
      FLASK_CONFIG: development
      DATABASE_URL: sqlite:////data/bom_data.db
      GUNICORN_WORKERS: 4
      CORS_ORIGINS: "http://localhost:5173,http://localhost:3000"
    volumes:
      - backend-data:/data
    ports:
      - "5000:8000"

  frontend:
    build:
      context: ./frontend
    environment:
      VITE_API_URL: http://localhost:5000
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  backend-data:
