[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "python init_db.py && gunicorn wsgi:app -c gunicorn.conf.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.environmentVariables]]
name = "FLASK_CONFIG"
value = "production"

[[deploy.environmentVariables]]
name = "PORT"
value = "8000"

[[deploy.environmentVariables]]
name = "GUNICORN_WORKERS"
value = "4"

[[deploy.environmentVariables]]
name = "PYTHONUNBUFFERED"
value = "1"