name: Discord Notifications

on:
  pull_request:
    branches: [ "main" ]
    types: [ "opened", "closed" ]
  push:
    branches: [ "main" ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification on PR Opened
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "A new pull request is ready for review!"
          embed-title: "PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
          embed-url: "${{ github.event.pull_request.html_url }}"
          embed-author-name: "${{ github.event.pull_request.user.login }}"
          embed-author-icon-url: "${{ github.event.pull_request.user.avatar_url }}"
          embed-color: 65535

      - name: Send Discord Notification on PR Merged
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "A pull request was just merged into main!"
          embed-title: "PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
          embed-url: "${{ github.event.pull_request.html_url }}"
          embed-author-name: "${{ github.event.pull_request.user.login }}"
          embed-author-icon-url: "${{ github.event.pull_request.user.avatar_url }}"
          embed-color: 65280
          
      - name: Send Discord Notification on Push
        if: github.event_name == 'push'
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "Code was pushed directly to main!"
          embed-title: "Direct push by ${{ github.actor }}"
          embed-url: "${{ github.event.compare }}"
          embed-author-name: "${{ github.actor }}"
          embed-color: 16776960 # Yellow
